
[build]
  publish = "dist"  # Carpeta donde se construye la app de Vue
  functions = "netlify/functions"  # Carpeta donde están las funciones

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
